# Generated by Django 4.1 on 2022-11-28 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("wallet", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mongodbuser",
            name="email",
        ),
        migrations.RemoveField(
            model_name="mongodbuser",
            name="user_name",
        ),
        migrations.AddField(
            model_name="mongodbuser",
            name="user",
            field=models.OneToOneField(
                default=20200101,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mongodbuser",
            name="wallet_address",
            field=models.CharField(default=2018, max_length=34),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="mongodbuser",
            name="date_of_birth",
            field=models.DateField(default="2020-01-01"),
        ),
    ]
