# Generated by Django 4.1 on 2022-11-28 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0002_remove_mongodbuser_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mongodbuser",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="mongodbuser",
            name="last_name",
        ),
        migrations.AlterField(
            model_name="mongodbuser",
            name="wallet_address",
            field=models.CharField(blank=True, max_length=34),
        ),
    ]
