# Generated by Django 4.1 on 2022-11-28 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0003_remove_mongodbuser_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mongodbuser",
            name="date_of_birth",
            field=models.DateField(),
        ),
    ]
